spring:
  jpa:
    database: HSQL
    hibernate:
      ddl-auto: create-drop

ribbon:
  IsSecure: false

security:
  basic:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
